//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HexEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_LIGHTBULB                   102
#define IDD_DIALOGBAR                   103
#define ID_INDICATOR_BIG_ENDIAN         103
#define ID_INDICATOR_FILE_LENGTH        104
#define ID_INDICATOR_HEX_ADDR           105
#define ID_INDICATOR_DEC_ADDR           106
#define ID_INDICATOR_VALUES             107
#define ID_INDICATOR_READONLY           108
#define ID_INDICATOR_OCCURRENCES        109
#define IDD_TIP                         109
#define ID_JUMP_HEX_ADDR                110
#define CG_IDS_TIPOFTHEDAY              111
#define CG_IDS_TIPOFTHEDAYMENU          112
#define IDS_COLORS                      112
#define CG_IDS_DIDYOUKNOW               113
#define CG_IDS_TIPOFTHEDAYMENU2         113
#define CG_IDS_FILE_ABSENT              114
#define CG_IDS_DIDYOUKNOW2              114
#define CG_IDP_FILE_CORRUPT             115
#define CG_IDS_FILE_ABSENT2             115
#define CG_IDS_TIPOFTHEDAYHELP          116
#define CG_IDP_FILE_CORRUPT2            116
#define IDD_CALC                        117
#define CG_IDS_TIPOFTHEDAYHELP2         117
#define IDS_WEB_ADDRESS                 118
#define IDS_WEB_REG_USER                119
#define IDS_WEB_HELP                    120
#define IDS_WEB_REG_MC                  121
#define IDS_WEB_UPGRADE                 122
#define IDS_WEB_FORUMS                  123
#define IDS_WEB_FAQ                     124
#define IDD_CALC_OLD                    125
#define IDD_CALC_NEW                    126
#define IDR_MAINFRAME                   128
#define IDR_NOTUSED                     128
#define IDR_HEXEDTYPE                   129
#define IDR_MAINFRAME1                  129
#define IDR_UNUSED                      129
#define IDB_FILE_OPENU                  130
#define ID_TOOL1                        130
#define IDI_NEW                         130
#define IDB_FILE_PRINTU                 131
#define IDR_MAINFRAME2                  131
#define ID_TOOL2                        131
#define IDB_AUTOFITU                    132
#define ID_TOOL3                        132
#define IDB_FONTU                       133
#define ID_TOOL4                        133
#define ID_TOOL5                        134
#define ID_TOOL6                        135
#define IDB_ASC_EBCU                    136
#define ID_TOOL7                        136
#define IDB_CONTROLU                    137
#define ID_TOOL8                        137
#define ID_TOOL9                        138
#define IDB_MARKU                       139
#define IDS_NEW                         139
#define IDB_GOTO_MARKU                  140
#define IDS_DEL                         140
#define IDD_PASSWORD                    141
#define IDS_UP                          141
#define IDS_DOWN                        142
#define IDB_EDIT_UNDOU                  143
#define IDS_NEW_TIP                     143
#define IDS_DEL2                        144
#define IDS_DEL_TIP                     144
#define IDB_BITMAP1                     149
#define IDD_FIND_HEX                    150
#define IDD_PROP_FILE                   151
#define IDD_FIND_NUMBER                 152
#define IDB_FILE_OPEND                  153
#define IDB_FILE_PRINTX                 154
#define IDB_FILE_PRINTD                 155
#define IDB_AUTOFITX                    156
#define IDB_AUTOFITD                    157
#define IDB_FONTX                       158
#define IDD_OPT_SYSTEM                  158
#define IDB_FONTD                       159
#define IDD_OPT_DEFDISPLAY              159
#define IDB_ADDR_TOGGLEU                160
#define IDB_ADDR_TOGGLEX                161
#define IDR_NOT_USED                    161
#define IDB_ADDR_TOGGLED                162
#define IDB_CHAR_TOGGLEU                163
#define IDD_PROP_DECIMAL                163
#define IDB_CHAR_TOGGLEX                164
#define IDD_PROP_FLOAT                  164
#define IDB_CHAR_TOGGLED                165
#define IDB_ASC_EBCX                    166
#define IDD_MULTIPLAY                   166
#define IDB_ASC_EBCD                    167
#define IDD_OPT_WINDOW                  167
#define IDB_CONTROLX                    168
#define IDD_OPT_PARTITIONS              168
#define IDB_CONTROLD                    169
#define IDD_OPT_MACRO                   169
#define IDB_GRAPHIC_TOGGLEU             170
#define IDD_PROP_IBMFP                  170
#define IDB_GRAPHIC_TOGGLED             171
#define IDB_GRAPHIC_TOGGLEX             172
#define IDB_MARKX                       173
#define IDB_MARKD                       174
#define IDB_GOTO_MARKD                  175
#define IDB_GOTO_MARKX                  176
#define IDB_AUTOFITS                    177
#define IDB_CONTROL1S                   178
#define IDB_CONTROL2S                   179
#define IDB_ADDR_TOGGLES                180
#define IDB_ASC_EBCS                    181
#define IDB_GRAPHIC_TOGGLES             182
#define IDB_CHAR_TOGGLES                183
#define IDB_EDIT_UNDOD                  184
#define IDB_EDIT_UNDOX                  185
#define IDB_FILE_SAVEU                  186
#define IDB_FILE_SAVED                  187
#define IDB_FILE_SAVEX                  188
#define IDB_FILE_PREVIEWU               189
#define IDB_EDIT_CUTU                   190
#define IDB_EDIT_COPYU                  191
#define IDB_EDIT_PASTEU                 192
#define IDB_EDIT_FINDPREVU              193
#define IDB_EDIT_FINDNEXTU              194
#define IDB_EDIT_FINDNEXTD              195
#define IDB_EDIT_FINDNEXTX              196
#define IDB_RS_FORWU                    197
#define IDB_RS_FORWD                    198
#define IDB_RS_FORWX                    199
#define IDB_EDIT_FINDPREVD              200
#define IDB_EDIT_FINDPREVX              201
#define IDB_RS_BACKD                    202
#define IDB_RS_BACKU                    203
#define IDB_RS_BACKX                    204
#define IDB_MODSU                       205
#define IDB_MODSD                       206
#define IDB_MODSX                       207
#define IDB_MODSS                       208
#define IDB_EDIT_RECU                   209
#define IDB_EDIT_PLAYU                  210
#define IDB_EDIT_COPYX                  211
#define IDB_EDIT_CUTX                   212
#define IDB_EDIT_PASTEX                 213
#define IDB_EDIT_PLAYX                  214
#define IDB_EDIT_RECX                   215
#define IDB_EDIT_COPYD                  216
#define IDB_EDIT_CUTD                   217
#define IDB_EDIT_PASTED                 218
#define IDB_EDIT_PLAYD                  219
#define IDB_EDIT_RECD                   220
#define IDB_FINCU                       221
#define IDB_FINCD                       222
#define IDB_FINCX                       223
#define IDB_FDECD                       224
#define IDB_FDECU                       225
#define IDB_FDECX                       226
#define IDB_EDIT_RECS                   227
#define IDB_REMOVE                      228
#define IDB_DEL                         228
#define IDB_ADD                         229
#define IDB_NEW                         229
#define IDD_EMAIL                       229
#define IDB_UP                          230
#define IDD_OPT_COLOURS                 230
#define IDB_DOWN                        231
#define IDB_DOWNU                       231
#define IDD_REGISTER                    231
#define IDR_EDITBAR                     232
#define IDD_ABOUT                       233
#define IDR_MISC                        233
#define IDI_ICON1                       233
#define IDB_DOWND                       234
#define IDD_MACROSAVE                   234
#define IDB_DOWNX                       235
#define IDD_OPT_SYSDISPLAY              235
#define IDB_UPD                         236
#define IDD_REG                         236
#define IDB_UPU                         237
#define IDD_OPT_COLOURS1                237
#define IDB_UPX                         238
#define IDD_ALGORITHM                   238
#define IDR_CONTEXT_ADDRESS             239
#define IDR_CONTEXT_HEX                 240
#define IDD_OPT_PRINT                   240
#define IDR_CONTEXT_CHAR                241
#define IDD_OPT_FILTERS                 241
#define IDR_CONTEXT_BARS                242
#define IDD_OPT_WINDOW1                 242
#define IDR_CONTEXT_STATBAR             243
#define IDD_PROP_FILE1                  243
#define IDR_CONTEXT_HIGHLIGHT           244
#define IDR_MAINFRAME3                  245
#define IDI_UP                          245
#define IDR_TOOLBAR                     245
#define IDR_VIEWBAR                     245
#define IDD_OPT_COLOURS2                245
#define IDR_STDBAR                      245
#define IDI_DOWN                        246
#define IDR_NAVBAR                      246
#define IDI_ARROW                       247
#define IDI_DEL                         247
#define IDR_FORMATBAR                   247
#define IDC_HIGHLIGHT                   248
#define IDR_MAINFRAME4                  248
#define IDD_FIND_REPLACE                249
#define IDD_FIND_SIMPLE                 250
#define IDD_FIND_TEXT                   251
#define IDR_PRINT_ARGS                  252
#define IDR_CONTEXT_SELECTION           253
#define IDR_MENUBUTTON                  254
#define IDR_CONTEXT_BOOKMARKS           255
#define IDI_DISPLAY                     256
#define IDI_COGS                        257
#define IDI_MACRO                       258
#define IDI_PRINTER                     259
#define IDI_WINDOW                      260
#define IDI_COLOUR                      261
#define IDI_FILTER                      262
#define IDD_NEW_SCHEME                  263
#define IDI_STRUCT                      263
#define IDD_MULTIPLAY1                  264
#define IDI_FOR                         264
#define IDD_MACRO_MESSAGE               265
#define IDI_IF                          265
#define IDB_IMAGELIST                   266
#define IDI_DATA                        266
#define IDD_STARTUP                     267
#define IDB_DEVIMAGES                   267
#define IDI_EVAL                        267
#define IDD_OPT_WINDISPLAY              268
#define IDI_JUMP                        268
#define IDB_LIGHTBULB1                  268
#define IDB_SEARCH                      268
#define IDD_PROP_DATE                   269
#define IDI_SWITCH                      269
#define IDD_RECENT_FILES                270
#define IDD_BOOKMARKS                   271
#define IDD_CLEAR_HIST                  274
#define IDD_PRINTDLG                    275
#define IDD_BM_FIND                     276
#define IDD_DFFD_DATA                   277
#define IDD_DFFD_STRUCT                 278
#define IDR_DFFD                        279
#define IDD_DFFD_FOR                    279
#define IDD_DFFD_IF                     280
#define IDR_CONTEXT_TABS                280
#define IDD_DFFD_GLOBAL                 281
#define IDD_SAVE_TEMPLATE               282
#define IDD_NEW_FILE                    284
#define IDD_CSRC                        287
#define IDD_OPEN_SPECIAL                289
#define IDD_PROP_PARENT                 290
#define IDD_FIND_PARENT                 291
#define IDD_DFFD_EVAL                   292
#define ID_NODE_EXPANDALL               293
#define IDD_DFFD_JUMP                   293
#define ID_STRUCT_INSERT                294
#define IDD_DFFD_USE_STRUCT             294
#define ID_STRUCT_ENCLOSEIN             295
#define IDD_PROP_INFO                   295
#define IDD_EXPLORER                    296
#define IDD_BOOKMARKS1                  297
#define IDD_COMPRESS                    298
#define ID_NAV_FORW_DUMMY               300
#define ID_NAV_BACK_DUMMY               301
#define IDB_BACK                        302
#define IDB_FORW                        303
#define IDR_EXPL                        303
#define IDB_REFRESH                     304
#define IDD_TPARSE                      304
#define IDB_PARENT                      305
#define IDD_TPARSE1                     305
#define IDR_FUNCTION                    305
#define IDB_VIEW                        306
#define ID_INTEGER_ABS                  306
#define IDD_PROP_CHAR1                  306
#define IDD_PROP_CHAR                   306
#define IDB_BACK1                       307
#define ID_INTEGER_MIN                  307
#define IDD_DFFD_SWITCH                 307
#define IDB_FORW1                       308
#define ID_INTEGER_MAX                  308
#define IDD_OPT_TIPS                    308
#define IDB_PARENT1                     309
#define ID_INTEGER_SIZEOF               309
#define IDD_PROP_REAL                   309
#define IDB_BACK_HOT                    310
#define ID_INTEGER_INT                  310
#define IDB_FORW_HOT                    311
#define ID_INTEGER_INT311               311
#define IDB_PARENT_HOT                  312
#define ID_INTEGER_ATOI                 312
#define IDB_VIEW1                       313
#define ID_INTEGER_STRLEN               313
#define IDB_VIEW_HOT                    314
#define ID_INTEGER_STRCHR               314
#define IDB_REFRESH1                    315
#define ID_INTEGER_STRSTR               315
#define IDB_REFRESH_HOT                 316
#define ID_INTEGER_SRTCMP               316
#define IDB_FLIP                        317
#define IDB_HORZ                        317
#define ID_Menu                         317
#define IDB_FLIP_HOT                    318
#define IDB_HORZ_HOT                    318
#define ID_REAL_ABS                     318
#define IDB_FLIP1                       319
#define ID_REAL_MIN                     319
#define IDB_FLIP1_HOT                   320
#define ID_REAL_MAX                     320
#define IDB_SHOW_HOT                    321
#define ID_REAL_ATOF                    321
#define IDB_TMP                         322
#define ID_REAL_POW                     322
#define IDB_VERT                        323
#define ID_INTEGER_POW                  323
#define IDB_VERT_HOT                    324
#define ID_REAL_POW324                  324
#define IDB_HIDE_HOT                    325
#define ID_REAL_SQRT                    325
#define IDB_SHOW                        326
#define ID_REAL_SIN                     326
#define IDB_HIDE                        327
#define ID_REAL_COS                     327
#define ID_REAL_TAN                     328
#define ID_REAL_ASIN                    329
#define ID_REAL_ACOS                    330
#define ID_REAL_ATAN                    331
#define ID_REAL_EXP                     332
#define ID_REAL_LOG                     333
#define ID_DATE_NOW                     334
#define ID_INTEGER_RAND                 335
#define ID_DATE_YEAR                    336
#define ID_DATE_MONTH                   337
#define ID_DATE_DAY                     338
#define ID_DATE_HOUR                    339
#define ID_DATE_MONUTE                  340
#define ID_DATE_SECOND                  341
#define ID_DATE_DATE                    342
#define ID_DATE_TIME                    343
#define ID_STRING_LEFT                  344
#define ID_STRING_RIGHT                 345
#define ID_STRING_MID                   346
#define ID_STRING_MID347                347
#define ID_BOOLEAN_FASLE                348
#define ID_BOOLEAN_TRUE                 349
#define ID_STRING_LTRIM                 350
#define ID_STRING_RTRIM                 351
#define IDI_ICON2                       353
#define IDI_ICON3                       354
#define IDI_TIPS                        355
#define ID_CHECKSUM_MD5                 357
#define ID_CONVERT_UPPERCASE            358
#define ID_CONVERT_LOWERCASE            359
#define ID_DFFD_HIDE                    360
#define ID_DFFD_SPLIT                   361
#define ID_DFFD_TAB                     362
#define ID_TEMPLATE_REFRESH             363
#define ID_TEMPLATE_ALLOWEDITING        364
#define ID_DFFD_NEW                     365
#define ID_DFFD_OPEN_OTHER_DUMMY        366
#define ID_DFFD_HELP                    367
#define ID_DFFD_SAVE                    368
#define ID_DFFD_SAVEAS                  369
#define ID_DFFD_SYNC                    370
#define ID_DFFD_AUTO_SYNC               371
#define ID_DFFD_REFRESH                 372
#define ID_DFFD_TOGGLE_EDIT             373
#define ID_DFFD_OPEN_TYPE_DUMMY         374
#define ID_DFFD_OPTIONS                 375
#define IDC_BULB                        1000
#define IDC_EDIT                        1000
#define IDC_PASSWORD_MASK               1000
#define IDC_STARTUP                     1001
#define IDC_HEX                         1001
#define IDC_PASSWORD_ENTER              1001
#define IDC_NEXTTIP                     1002
#define IDC_DECIMAL                     1002
#define IDC_PASSWORD_REENTER            1002
#define IDC_OCTAL                       1003
#define IDC_TIPSTRING                   1004
#define IDC_BINARY                      1004
#define IDC_PASSWORD_NOTE               1004
#define IDC_64BIT                       1005
#define IDC_PASSWORD_MIN                1005
#define IDC_32BIT                       1006
#define IDC_PASSWORD_SPIN               1006
#define IDC_16BIT                       1007
#define IDC_8BIT                        1008
#define IDC_DIGIT_0                     1010
#define IDC_DIGIT_1                     1011
#define IDC_DIGIT_2                     1012
#define IDC_DIGIT_3                     1013
#define IDC_DIGIT_4                     1014
#define IDC_DIGIT_5                     1015
#define IDC_DIGIT_6                     1016
#define IDC_BUTTON_URL                  1016
#define IDC_DIGIT_7                     1017
#define IDC_DIGIT_8                     1018
#define IDC_DIGIT_9                     1019
#define IDC_DIGIT_A                     1020
#define IDC_DIGIT_B                     1021
#define IDC_DIGIT_C                     1022
#define IDC_DIGIT_D                     1023
#define IDC_DIGIT_E                     1024
#define IDC_SEARCH                      1025
#define IDC_DIGIT_F                     1025
#define ID_SEARCH_FORW                  1026
#define ID_SEARCH_BACK                  1028
#define IDC_MEM_GET                     1028
#define IDC_MARK_GET                    1029
#define ID_RS_BACK                      1030
#define IDC_MARK_AT                     1030
#define ID_RS_FORW                      1031
#define IDC_SEL_GET                     1031
#define IDC_SEL_AT                      1032
#define IDC_SEL_LEN                     1034
#define IDC_EOF_GET                     1035
#define IDC_BACKSPACE                   1039
#define IDC_CLEAR_ENTRY                 1040
#define IDC_CLEAR                       1041
#define IDC_EQUALS                      1042
#define IDC_BACKUP                      1043
#define IDC_GO                          1043
#define IDC_OPEN_DISPLAY_CHAR           1044
#define IDC_RESTORE                     1044
#define IDC_BACKUP_SPACE                1044
#define IDC_OPEN_AUTOFIT                1045
#define IDC_HEX_UCASE                   1045
#define IDC_BACKUP_PROMPT               1045
#define IDC_SAVE_EXIT                   1046
#define IDC_OPEN_ADDR_DEC               1046
#define IDC_MEM_STORE                   1046
#define IDC_MDITABS                     1046
#define IDC_SAVE_NOW                    1047
#define IDC_OPEN_GRAPHIC                1047
#define IDC_MEM_CLEAR                   1047
#define IDC_TABSBOTTOM                  1047
#define IDC_OPEN_CONTROL                1048
#define IDC_NICE_ADDR                   1048
#define IDC_MEM_ADD                     1048
#define IDC_ONE_ONLY                    1048
#define IDC_OPEN_EBCDIC                 1049
#define IDC_FILE_NAME                   1049
#define IDC_MEM_SUBTRACT                1049
#define IDC_LARGE_CURSOR                1049
#define IDC_BG_SEARCH                   1049
#define IDC_OPEN_OVERTYPE               1050
#define IDC_FILE_TYPE                   1050
#define IDC_SHELLOPEN                   1050
#define IDC_MARK_STORE                  1050
#define IDC_SHOW_OTHER                  1050
#define IDC_INFO_KEYWORDS               1050
#define IDC_OPEN_INSERT                 1051
#define IDC_MARK_CLEAR                  1051
#define IDC_CLEAR_HIST                  1051
#define IDC_INFO_COMMENTS               1051
#define IDC_OPEN_READONLY               1052
#define IDC_MARK_ADD                    1052
#define IDC_BACKUP_IF_SIZE              1052
#define IDC_OPEN_ALLOW_MODS             1053
#define IDC_MARK_SUBTRACT               1053
#define IDC_OPEN_MAX                    1054
#define IDC_MARK_AT_STORE               1054
#define IDC_OPEN_OEM                    1055
#define IDC_SEL_STORE                   1055
#define IDC_SEL_AT_STORE                1056
#define IDC_SEL_LEN_STORE               1057
#define IDC_POW                         1060
#define IDC_MOD                         1061
#define IDC_DIVIDE                      1062
#define IDC_MULTIPLY                    1063
#define IDC_SUBTRACT                    1064
#define IDC_ADDOP                       1065
#define IDC_CHAR_HEX                    1066
#define IDC_GTR                         1066
#define IDC_CHAR_DEC                    1067
#define IDC_DEC_8BIT                    1067
#define IDC_LESS                        1067
#define IDC_CHAR_OCTAL                  1068
#define IDC_DEC_16BIT                   1068
#define IDC_XOR                         1068
#define IDC_CHAR_BINARY                 1069
#define IDC_DEC_32BIT                   1069
#define IDC_FILE_PATH                   1069
#define IDC_OR                          1069
#define IDC_CHAR_ASCII                  1070
#define IDC_DEC_64BIT                   1070
#define IDC_AND                         1070
#define IDC_CHAR_EBCDIC                 1071
#define IDC_BE_8BIT                     1071
#define IDC_FILE_MODIFIED               1071
#define IDC_ROL                         1071
#define IDC_BE_16BIT                    1072
#define IDC_FILE_ACCESSED               1072
#define IDC_CHAR_UNICODE                1072
#define IDC_ROR                         1072
#define IDC_BE_32BIT                    1073
#define IDC_FILE_SIZE                   1073
#define IDC_LSL                         1073
#define IDC_PLACE_HOLDER                1073
#define IDC_BE_64BIT                    1074
#define IDC_FP_VAL                      1074
#define IDC_LSR                         1074
#define IDC_INFO_VIEW_TIME              1074
#define IDC_FP_MANT                     1075
#define IDC_ASR                         1075
#define IDC_INFO_EDIT_TIME              1075
#define IDC_FP_EXP                      1076
#define IDC_INFO_DISK_SIZE              1076
#define IDC_SUBJECT                     1077
#define IDC_PRINT_HEADER                1077
#define IDC_FILE_READONLY               1078
#define IDC_NAME                        1078
#define IDC_PRINT_FOOTER                1078
#define IDC_FILE_HIDDEN                 1079
#define IDC_ADDRESS                     1079
#define IDC_INSTALL_CODE                1079
#define IDC_FIND_GROUP                  1079
#define IDC_FIND_HEX                    1080
#define IDC_FILE_SYSTEM                 1080
#define IDC_UNARY_SIGN                  1080
#define IDC_ATTACHMENT                  1080
#define IDC_FIND_ASCII                  1081
#define IDC_UNARY_INC                   1081
#define IDC_FILE_ARCHIVED               1081
#define IDC_FIND_EBCDIC                 1082
#define IDC_UNARY_DEC                   1082
#define IDC_FIND_UNICODE                1083
#define IDC_UNARY_NOT                   1083
#define IDC_UNARY_REV                   1084
#define IDC_COMBO                       1085
#define IDC_UNARY_FLIP                  1085
#define IDC_REFRESH_NEVER               1086
#define IDC_BUG                         1086
#define IDC_UNARY_ROL                   1086
#define IDC_MACHINE                     1086
#define IDC_PRINT_SPACE1                1086
#define IDC_ADDRESS_FILE                1086
#define IDC_DFFD_SPLIT                  1086
#define ID_FONT_INC                     1087
#define IDC_REFRESH_SECS                1087
#define IDC_ENHANCE                     1087
#define IDC_UNARY_ROR                   1087
#define IDC_USER                        1087
#define IDC_PRINT_SPACE1HALF            1087
#define IDC_ADDRESS_SPECIFIED           1087
#define IDC_DFFD_TAB                    1087
#define ID_FONT_DEC                     1088
#define IDC_UNICODE_DESC                1088
#define IDC_REFRESH_PLAYS               1088
#define IDC_OTHER                       1088
#define IDC_UNARY_LSL                   1088
#define IDC_SITE                        1088
#define IDC_PRINT_SPACE2                1088
#define IDC_CHAR                        1089
#define IDC_UNARY_LSR                   1089
#define IDC_AUTOFIT                     1090
#define IDC_DEC_UNSIGNED                1090
#define IDC_REFRESH_KEYS                1090
#define IDC_UNARY_ASR                   1090
#define IDC_COLS                        1091
#define IDC_DEC_2COMP                   1091
#define IDC_UNARY_AT                    1091
#define IDC_OFFSET                      1092
#define IDC_DEC_1COMP                   1092
#define IDC_UNARY_SQUARE                1092
#define IDC_GROUPING                    1093
#define IDC_DEC_SIGN_MAG                1093
#define IDC_UNARY_CUBE                  1093
#define IDC_NUM_KEYS                    1094
#define IDC_UNARY_SQUARE_ROOT           1094
#define IDC_VERTBUFFER                  1094
#define IDC_SPIN_COLS                   1095
#define IDC_NUM_PLAYS                   1095
#define IDC_UNARY_FACTORIAL             1095
#define IDC_SPIN_EXPORT_LINELEN         1095
#define IDC_SPIN_DFFD_ARRAY_MAX         1095
#define IDC_SPIN_OFFSET                 1096
#define IDC_SPIN_RECENT_FILES           1096
#define IDC_SPIN_GROUPING               1097
#define IDC_COLS_DESC                   1098
#define IDC_SPIN_GROUPING2              1098
#define IDC_SPIN_KEYS                   1098
#define IDC_SPIN_GROUPING3              1099
#define IDC_SPIN_PLAYS                  1099
#define IDC_DISPLAY_HEX                 1099
#define IDC_SPIN_VERTBUFFER             1099
#define IDC_NAMES                       1100
#define IDC_ADD                         1101
#define IDC_REMOVE                      1102
#define IDC_RESET                       1103
#define IDC_VALIDATE                    1103
#define IDC_DEFAULT                     1104
#define IDC_SCHEMES                     1104
#define IDC_RANGES                      1105
#define IDC_COLOUR                      1106
#define IDC_ADD_SCHEME                  1107
#define IDC_REMOVE_SCHEME               1108
#define IDC_FP_64BIT                    1110
#define IDC_FP_32BIT                    1111
#define IDC_REFRESH_PROPS               1115
#define IDC_REFRESH_BARS                1116
#define IDC_HALT0                       1117
#define IDC_HALT1                       1118
#define IDC_HALT2                       1119
#define IDC_NUM_SECS                    1120
#define IDC_SPIN_SECS                   1121
#define IDC_DESC_SECS                   1122
#define IDC_DESC_KEYS                   1123
#define IDC_DESC_PLAYS                  1124
#define IDC_PLAYS                       1125
#define IDC_PLAY_OPTIONS                1126
#define IDC_TEXT_HALT1                  1127
#define IDC_TEXT_HALT0                  1128
#define IDC_BIG_ENDIAN                  1129
#define IDC_IBMFP_VAL                   1130
#define IDC_DATE_LOCAL_TIME             1130
#define IDC_IBMFP_MANT                  1131
#define IDC_IBMFP_EXP                   1132
#define IDC_IBMFP_32BIT                 1133
#define IDC_IBMFP_64BIT                 1134
#define IDC_BOX                         1135
#define IDC_CURRENT                     1136
#define IDC_NEW                         1137
#define IDC_DOWN                        1138
#define IDC_TO                          1139
#define IDC_CHANGE_TRACKING             1140
#define IDC_BORDERS                     1141
#define IDC_SYSTYPE                     1142
#define IDC_TEXT                        1143
#define IDC_DEL                         1144
#define IDC_VERSION                     1144
#define IDC_UP                          1145
#define IDC_OPEN_FONT                   1145
#define IDC_DFFD_DOWN                   1146
#define IDC_OP_DISPLAY                  1147
#define IDC_REGISTER                    1148
#define IDC_LINE1                       1149
#define IDC_LINE2                       1150
#define IDC_LINE3                       1151
#define IDC_LINE4                       1152
#define IDC_EMAIL_HELP                  1153
#define IDC_MACRO_HELP                  1154
#define IDC_LOADMACRO                   1155
#define IDC_MACRO_NAME                  1155
#define IDC_MACRO_COMMENT               1156
#define IDC_DESC_COLOUR                 1156
#define IDC_SAVEMACRO                   1157
#define IDC_EMAIL                       1157
#define IDC_REG_EMAIL                   1157
#define IDC_MACRODIR                    1158
#define IDC_REG_CODE                    1158
#define IDC_DESC_NAME                   1159
#define IDC_USER_NAME                   1160
#define IDC_REG_HELP                    1161
#define IDC_REG_WEB                     1162
#define IDC_COSTS                       1163
#define IDC_REG_FORM                    1164
#define IDC_COLOUR_SELECT               1164
#define IDC_BIG_ENDIAN_FILE_ACCESS      1164
#define IDC_ALG                         1166
#define IDC_ALG_BLOCKLEN                1167
#define IDC_ALG_KEYLEN                  1168
#define IDC_ALG_NOTE                    1169
#define IDC_PASSWORD_DESC               1170
#define IDC_FORMAT                      1171
#define IDC_DATE_FORMAT                 1171
#define IDC_DFFD_FORMAT                 1171
#define IDC_DATE                        1172
#define IDC_DATE_DATE                   1172
#define IDC_TIME                        1173
#define IDC_DATE_TIME                   1173
#define IDC_FIRST                       1174
#define IDC_DATE_FIRST                  1174
#define IDC_LAST                        1175
#define IDC_DATE_LAST                   1175
#define IDC_NOW                         1176
#define IDC_DATE_NOW                    1176
#define IDC_STORE                       1177
#define IDC_DATE_STORE                  1177
#define IDC_NOW2                        1178
#define IDC_DATE_NULL                   1178
#define IDC_FORMAT_DESC                 1179
#define IDC_DATE_FORMAT_DESC            1179
#define IDC_DATE_RESTORE                1180
#define IDC_DATE_DISPLAY                1181
#define IDC_DATE_BIG_ENDIAN             1182
#define IDC_PRINT_LEFT                  1185
#define IDC_PRINT_TOP                   1186
#define IDC_PRINT_BOTTOM                1187
#define IDC_PRINT_RIGHT                 1188
#define IDC_HEADER_OPTS                 1189
#define IDC_FOOTER_OPTS                 1190
#define IDC_NET_RETAIN                  1190
#define IDC_CLEAR_SEARCH                1190
#define IDC_DFFD_ON                     1190
#define IDC_GRID                        1191
#define IDC_CLEAR_RECENT_FILE           1191
#define IDC_PRINT_HEADER_EDGE           1191
#define IDC_FILE_CREATED                1192
#define IDC_MAX                         1192
#define IDC_CLEAR_BOOKMARKS             1192
#define IDC_PRINT_FOOTER_EDGE           1192
#define IDC_VISUALIZATIONS              1193
#define IDC_CLEAR_ON_EXIT               1193
#define IDC_PASSWORD_HELP               1194
#define IDC_ALGORITHM_HELP              1195
#define IDC_OPEN_FILES                  1196
#define IDC_OPEN_RO                     1197
#define IDC_DISPLAY_RESET               1198
#define IDC_SHOW_AREA                   1199
#define IDC_CHARSET                     1200
#define IDC_CONTROL                     1201
#define IDC_INSERT                      1202
#define IDC_ADDR_DEC                    1204
#define IDC_FONT                        1205
#define IDC_SAVE_DEFAULT                1206
#define IDC_MODIFY                      1207
#define IDC_GROUPING_DESC               1208
#define IDC_CHARSET_DESC                1209
#define IDC_CONTROL_DESC                1210
#define IDC_INSERT_DESC                 1211
#define IDC_COLOUR_PICKER               1212
#define IDC_VERTBUFFER_DESC             1212
#define IDC_SCHEME_NAME                 1213
#define IDC_SCHEME_LIST                 1214
#define IDC_PLAY_NAME                   1216
#define IDC_MACRO_MESSAGE               1217
#define IDC_EXPORT_ADDRESS              1218
#define IDC_DISP_RESET                  1219
#define IDC_MORE                        1220
#define IDC_BACKUP_SIZE                 1220
#define IDC_EXPORT_LINELEN              1221
#define IDC_RECENT_FILES                1222
#define IDC_GRID_RFL                    1223
#define IDC_REMOVE_FILES                1224
#define IDC_BOOKMARK_GOTO               1225
#define IDC_BOOKMARK_REMOVE             1226
#define IDC_BOOKMARK_ADD                1227
#define IDC_BOOKMARKS_VALIDATE          1228
#define IDC_GRID_BL                     1229
#define IDC_BOOKMARK_NAME               1231
#define IDC_NET_RETAIN_DESC             1232
#define IDC_FILES_SELECTED              1233
#define IDC_DFFD_FORMAT_STRING          1234
#define IDC_DFFD_FORMAT_REAL            1235
#define IDC_DFFD_FORMAT_DATE            1236
#define IDC_DFFD_FORMAT_CHAR            1237
#define IDC_DFFD_FORMAT_INT             1238
#define IDC_DFFD_FORMAT_UINT            1239
#define IDC_DFFD_ARRAY_MAX              1240
#define IDC_DFFD_GROUP2                 1241
#define IDC_DFFD_GROUP1                 1242
#define IDC_DESC_DFFD_ARRAY_MAX         1243
#define IDC_DESC_DFFD_FORMAT_CHAR       1244
#define IDC_DESC_DFFD_FORMAT_INT        1245
#define IDC_DESC_DFFD_FORMAT_UINT       1246
#define IDC_DESC_DFFD_FORMAT_STRING     1247
#define IDC_DESC_DFFD_FORMAT_REAL       1248
#define IDC_DESC_DFFD_FORMAT_DATE       1249
#define IDC_PRINT_BORDER                1252
#define IDC_PRINT_HEADINGS              1253
#define IDC_PRINT_OPTIONS               1253
#define IDC_PRINT_DUP_LINES             1255
#define IDC_FIND_NEXT                   1257
#define IDC_FIND_REPLACE                1258
#define IDC_FIND_REPLACE_ALL            1259
#define IDC_FIND_COMBINED_STRING        1260
#define IDC_FIND_TEXT_STRING            1261
#define IDC_FIND_HEX_STRING             1262
#define IDC_FIND_MASK                   1263
#define IDC_FIND_NUM_STRING             1264
#define IDC_FIND_REPLACE_STRING         1265
#define IDC_FIND_HELP                   1267
#define IDC_FIND_MASK_DESC              1268
#define IDC_FIND_MESSAGE                1269
#define IDC_FIND_DESC                   1270
#define IDC_FIND_DIRN_UP                1271
#define IDC_FIND_DIRN_DOWN              1272
#define IDC_FIND_SCOPE_SELECTION        1273
#define IDC_FIND_SCOPE_TOMARK           1274
#define IDC_FIND_SCOPE_TOEND            1275
#define IDC_FIND_SCOPE_FILE             1276
#define IDC_FIND_SCOPE_ALL              1277
#define IDC_FIND_MATCH_CASE             1278
#define IDC_FIND_WHOLE_WORD             1279
#define IDC_FIND_TYPE_ASCII             1280
#define IDC_FIND_TYPE_EBCDIC            1281
#define IDC_FIND_TYPE_UNICODE           1282
#define IDC_FIND_ALLOW_WILDCARD         1285
#define IDC_FIND_WILDCARD_CHAR          1286
#define IDC_FIND_USE_MASK               1287
#define IDC_FIND_ALIGN1                 1290
#define IDC_FIND_ALIGN2                 1291
#define IDC_FIND_ALIGN4                 1292
#define IDC_FIND_ALIGN8                 1293
#define IDC_FIND_BIG_ENDIAN             1296
#define IDC_FIND_NUMBER_FORMAT          1297
#define IDC_FIND_NUMBER_SIZE            1298
#define IDC_BOOKMARKS_HELP              1300
#define IDC_RECENT_FILES_HELP           1301
#define IDC_SCHEME_HELP                 1302
#define IDC_PLAY_HELP                   1303
#define IDC_CLEAR_HELP                  1304
#define IDC_BM_FIND_APPEND              1305
#define IDC_BM_FIND_MESS                1306
#define IDC_BM_FIND_OVERWRITE           1307
#define IDC_FIND_BOOKMARK_ALL           1308
#define IDC_FIND_BOOKMARK_PREFIX        1309
#define IDC_DFFD_TYPE                   1312
#define IDC_DFFD_LENGTH                 1314
#define IDC_DFFD_DOMAIN                 1315
#define IDC_DFFD_COUNT                  1315
#define IDC_DFFD_BIG_ENDIAN             1317
#define IDC_DFFD_READ_ONLY              1318
#define IDC_DFFD_DISPLAY                1319
#define IDC_DFFD_UNITS                  1320
#define IDC_DFFD_TYPE_NAME              1321
#define IDC_DFFD_COMMENTS               1322
#define IDC_DFFD_NAME                   1323
#define IDC_DFFD_FORMAT_DESC            1324
#define IDC_DFFD_ELT                    1324
#define IDC_DFFD_LENGTH_DESC            1325
#define IDC_DFFD_ELSE_ELT               1325
#define IDC_DFFD_DOMAIN_DESC            1326
#define IDC_DFFD_UNITS_DESC             1327
#define IDC_DFFD_DISPLAY_DESC           1328
#define ID_DFFD_PREV                    1329
#define ID_DFFD_NEXT                    1330
#define IDC_DFFD_ELEMENTS               1331
#define IDC_DFFD_COUNT_VAR              1331
#define ID_DFFD_CLONE                   1331
#define IDC_DFFD_INSERT                 1332
#define IDC_DFFD_STOP_VAR               1332
#define IDC_DFFD_DELETE                 1333
#define IDC_DFFD_EDIT                   1334
#define IDC_DFFD_REPLACE                1335
#define IDC_DFFD_STOP                   1336
#define IDC_DFFD_ELSE_EDIT              1336
#define IDC_DFFD_CONDITION              1337
#define IDC_DFFD_UP                     1338
#define IDC_DFFD_ELSE_REPLACE           1338
#define IDC_DFFD_CONDITION_VAR          1339
#define IDC_DFFD_LENGTH_VAR             1340
#define IDC_DFFD_DOMAIN_VAR             1341
#define IDC_WEB_ADDRESS                 1341
#define IDC_WEB_CHECK                   1342
#define IDC_DFFD_ASCII                  1343
#define IDC_DFFD_ANSI                   1344
#define IDC_DFFD_OEM                    1345
#define IDC_DFFD_EBCDIC                 1346
#define IDC_DFFD_DEFAULT_READ_ONLY      1347
#define IDC_DFFD_DEFAULT_BIG_ENDIAN     1348
#define IDC_SAVEAS                      1349
#define IDC_MESSAGE                     1350
#define IDC_IMPORT_HIGHLIGHT            1351
#define IDC_ELT_SIZE                    1352
#define IDC_ELT_OFFSET                  1353
#define IDC_DISCON                      1354
#define IDC_DECIMAL_SIZE                1355
#define IDC_HEX_SIZE                    1356
#define IDC_FILL_HEX                    1357
#define IDC_FILL_STRING                 1358
#define IDC_FILL_RANDOM                 1359
#define IDC_FILL_NUMBER                 1360
#define IDC_FILL_HEX_VALUE              1361
#define IDC_FILL_STRING_VALUE           1362
#define IDC_FILL_CLIPBOARD              1363
#define IDC_FILL_NUMBER_VALUE           1364
#define IDC_FILL_STRING_CHARSET         1365
#define IDC_FILL_CLIPBOARD_SAMPLE       1366
#define IDC_FILL_NUMBER_TYPE            1367
#define IDC_CSRC_INT_SIZE               1368
#define IDC_FILL_SIZE_DATA              1368
#define IDC_CSRC_FLOAT_SIZE             1369
#define IDC_FILL_SIZE_CALC              1369
#define IDC_FILL_RANDOM_RANGE           1370
#define IDC_SPIN_DECIMAL_SIZE           1371
#define IDC_DESC_FILL_STRING_CHARSET    1372
#define IDC_DESC_FILL_NUMBER_TYPE       1373
#define IDC_FILL_SIZE_SPECIFIED         1374
#define IDC_FILL_CLIPBOARD_LENGTH       1375
#define IDC_CSRC_STRING                 1376
#define IDC_SIZE_FACTOR                 1376
#define IDC_CSRC_CHAR                   1377
#define IDC_SPIN_SIZE_FACTOR            1377
#define IDC_CSRC_INT                    1378
#define IDC_SIZE_LENGTH                 1378
#define IDC_CSRC_INT_TYPE               1379
#define IDC_CSRC_FLOAT                  1380
#define IDC_CSRC_ADDRESS                1381
#define IDC_CSRC_INDENT                 1382
#define IDC_CSRC_INDENT_SPIN            1383
#define IDC_ACTIVATE                    1384
#define IDC_OPEN_TREE                   1385
#define IDC_DFFD_ALLOW_EDIT             1386
#define IDC_OPEN_INFO                   1387
#define IDC_PRINT_UNITS                 1388
#define IDC_CSRC_HELP                   1389
#define IDC_DFFD_EXPR                   1390
#define IDC_DFFD_EXPR_VAR               1391
#define IDC_DFFD_DISPLAY_ERROR          1392
#define IDC_DFFD_DISPLAY_RESULT         1393
#define IDC_DFFD_OFFSET                 1394
#define IDC_DFFD_OFFSET_VAR             1395
#define IDC_DFFD_ORIGIN                 1396
#define IDC_DFFD_ELSE                   1400
#define IDC_DFFD_IF_ELT                 1401
#define IDC_DFFD_IF_EDIT                1402
#define IDC_DFFD_IF_REPLACE             1403
#define IDC_DFFD_NAME_DESC              1404
#define IDC_DFFD_STRUCT                 1405
#define IDC_DFFD_STRUCT_VAR             1406
#define IDC_DFFD_TYPE_NAME_DESC         1407
#define IDC_FILL_DISK                   1408
#define IDC_DESC_FILL_CLIPBOARD_LENGTH  1409
#define IDC_FILL_HELP                   1410
#define IDC_BUTTON1                     1411
#define IDC_BASE_GROUP                  1414
#define IDC_BITS_GROUP                  1415
#define IDC_INFO_CATEGORY               1416
#define IDC_INFO_SIZE                   1417
#define IDC_SELECT_FONT                 1418
#define IDC_BOOKMARK_NAME_DESC          1420
#define IDC_EXPLORER_TREE               1421
#define IDC_EXPLORER_LIST               1422
#define IDC_FOLDER_BACK                 1424
#define IDC_FOLDER_FORW                 1425
#define IDC_FOLDER_PARENT               1426
#define IDC_FOLDER_NAME                 1427
#define IDC_FOLDER_FILTER               1428
#define IDC_FOLDER_REFRESH              1429
#define IDC_FOLDER_FLIP                 1430
#define IDC_FOLDER_VIEW                 1431
#define IDC_EXPLORER                    1432
#define IDC_FILTER_OPTS                 1433
#define IDC_ATTACH                      1434
#define IDC_FOLDER_HIDDEN               1434
#define IDC_ATTACHMENT_BROWSE           1435
#define IDC_EDIT1                       1436
#define IDC_PTR_SIZE2                   1437
#define IDC_PTR_SIZE4                   1438
#define IDC_PTR_SIZE8                   1439
#define IDC_FUNC_PTR2                   1440
#define IDC_FUNC_PTR4                   1441
#define IDC_FUNC_PTR8                   1442
#define IDC_PACK1                       1443
#define IDC_PACK2                       1444
#define IDC_PACK4                       1445
#define IDC_PACK8                       1446
#define IDC_PACK16                      1447
#define IDC_VALUES_CUSTOM               1448
#define IDC_VALUES_WINDOWS              1449
#define IDC_TYPES_STD                   1450
#define IDC_TYPES_COMMON                1451
#define IDC_TYPES_WINDOWS               1452
#define IDC_TYPES_CUSTOM                1453
#define IDC_TYPES_SAVE                  1454
#define IDC_TYPES_SAVE2                 1455
#define IDC_SOURCE_CODE                 1458
#define IDC_VALUES_SAVE                 1459
#define IDC_PACK_GROUP                  1460
#define IDC_VALUES_GROUP                1462
#define IDC_TYPES_GROUP                 1463
#define IDC_PROP_DESC                   1464
#define IDC_FILE_CREATED_DESC           1465
#define IDC_FILE_MODIFIED_DESC          1466
#define IDC_FILE_ACCESSED_DESC          1467
#define IDC_FILE_READONLY_DESC          1468
#define IDC_FILE_HIDDEN_DESC            1469
#define IDC_FILE_SYSTEM_DESC            1470
#define IDC_FILE_ARCHIVED_DESC          1471
#define IDC_STATIC1                     1472
#define IDC_STATIC2                     1473
#define IDC_DESC_DECIMAL_SIZE           1474
#define IDC_STATIC3                     1475
#define IDC_DESC_HEX_SIZE               1476
#define IDC_STATIC4                     1477
#define IDC_OPEN_SHARED                 1478
#define IDC_HEX_HIST                    1479
#define IDC_DEC_HIST                    1480
#define IDC_VARS                        1481
#define IDC_FUNC                        1482
#define IDC_CHAR_ACP                    1483
#define IDC_MULTIBYTE_DESC              1484
#define IDC_MULTIBYTE_HOLDER            1485
#define IDC_CODE_PAGE                   1486
#define IDC_CHAR_MULTIBYTE              1487
#define IDC_DFFD_CASES                  1490
#define IDC_DFFD_SWITCH_EXPR            1491
#define IDC_DFFD_CASE_RANGE             1492
#define IDC_DFFD_SWITCH_EXPR_VAR        1493
#define IDC_DFFD_BITFIELD               1494
#define IDC_DFFD_BITFIELD_DIRN          1495
#define IDC_DFFD_BITFIELD_BITS          1496
#define IDC_SPIN_BITFIELD_BITS          1497
#define IDC_DFFD_BITFIELD_BITS_DESC     1500
#define IDC_DFFD_BITFIELD_DIRN_DESC     1501
#define IDC_DFFD_TREE_DISPLAY           1502
#define IDC_COMPRESSION_LEVEL_DEFAULT   1503
#define IDC_COMPRESSION_WINDOW_SIZE_DEFAULT 1504
#define IDC_COMPRESSION_LEVEL_SPIN      1505
#define IDC_COMPRESSION_WINDOW_SIZE_SPIN 1506
#define IDC_COMPRESSION_HEADER_RAW      1507
#define IDC_COMPRESSION_HEADER_ZLIB     1508
#define IDC_COMPRESSION_HEADER_GZIP     1509
#define IDC_COMPRESSION_MEMORY_USAGE_SPIN 1510
#define IDC_COMPRESSION_MEMORY_USAGE_DEFAULT 1511
#define IDC_COMPRESSION_STRATEGY_DEFAULT 1512
#define IDC_COMPRESSION_STRATEGY_FILTERED 1513
#define IDC_COMPRESSION_STRATEGY_HUFFMAN 1514
#define IDC_COMPRESSION_STRATEGY_RLE    1515
#define IDC_COMPRESSION_STRATEGY_FIXED  1516
#define IDC_COMPRESSION_WINDOW_SIZE     1517
#define IDC_COMPRESSION_MEMORY_USAGE    1518
#define IDC_COMPRESSION_SYNC            1519
#define IDC_COMPRESSION_LEVEL           1520
#define IDC_RELMASK                     1521
#define IDC_ALIGN                       1522
#define IDC_ALIGN_SELECT                1523
#define IDC_ALIGN_SPIN                  1524
#define IDC_OFFSET_SPIN                 1525
#define IDC_COMPRESS_HELP               1526
#define IDC_SLIDER                      1527
#define IDC_RELATIVE                    1528
#define IDC_FP_FORMAT                   1529
#define IDC_FP_GROUP                    1530
#define IDC_FP_EXP_DESC                 1531
#define IDC_FP_DESC                     1532
#define IDC_CATEGORY_SELECT             1533
#define IDC_INFO_CATEGORY_SELECT        1533
#define ID_AUTOFIT                      32771
#define ID_FONT                         32772
#define ID_ADDR_TOGGLE                  32773
#define ID_CHAR_TOGGLE                  32774
#define ID_ASC_EBC                      32775
#define ID_GRAPHIC_TOGGLE               32776
#define ID_CONTROL                      32777
#define ID_GOTO_MARK                    32780
#define ID_MARK                         32781
#define IDC_JUMP_HEX                    32782
#define ID_VIEW_TOOLBARS                32782
#define IDC_JUMP_DEC                    32783
#define ID_SEARCH_HEX                   32791
#define ID_SEARCH_ASCII                 32792
#define ID_SEARCH_ICASE                 32793
#define ID_VIEW_EDITBAR                 32794
#define ID_JUMP_DEC_ADDR                32795
#define ID_ALLOW_MODS                   32796
#define ID_CONTROL_TOGGLE               32797
#define ID_OPTIONS                      32798
#define ID_INSERT                       32800
#define ID_RECORD                       32801
#define ID_PLAY                         32802
#define ID_EDIT_COMPARE                 32803
#define ID_WINDOW_NEXT                  32804
#define ID_PROPERTIES                   32806
#define ID_INC_BYTE                     32807
#define ID_INC_16BIT                    32808
#define ID_DEC_16BIT                    32812
#define ID_DEC_BYTE                     32813
#define ID_DEC_32BIT                    32814
#define ID_DEC_64BIT                    32815
#define ID_INC_32BIT                    32816
#define ID_INC_64BIT                    32817
#define ID_FLIP_16BIT                   32818
#define ID_FLIP_32BIT                   32819
#define ID_FLIP_64BIT                   32820
#define ID_SELECT_ALL                   32821
#define ID_SEARCH_SEL                   32822
#define ID_EDIT_WRITEFILE               32823
#define ID_COPY_CCHAR                   32824
#define ID_COPY_HEX                     32825
#define ID_PASTE_ASCII                  32826
#define ID_PASTE_UNICODE                32827
#define ID_PASTE_EBCDIC                 32828
#define ID_OPTIONS2                     32829
#define ID_EDIT_READFILE                32830
#define ID_OPTIONS3                     32831
#define ID_MULTI_PLAY                   32832
#define ID_EXTENDTO_MARK                32833
#define ID_SWAP_MARK                    32834
#define ID_EDIT_FIND2                   32837
#define ID_HELP_EMAIL                   32838
#define ID_SCROLL_UP                    32839
#define ID_SCROLL_DOWN                  32840
#define ID_REDRAW                       32841
#define ID_SWAP                         32842
#define ID_START_LINE                   32843
#define ID_DEL                          32844
#define ID_OEM_TOGGLE                   32846
#define ID_EDIT_GOTO                    32847
#define ID_CALCULATOR                   32849
#define ID_TEST                         32850
#define ID_DOCTEST                      32851
#define ID_TEST2                        32852
#define ID_VIEWTEST                     32853
#define ID_WEB_PAGE                     32854
#define ID_INVERT                       32856
#define ID_NEG_BYTE                     32857
#define ID_NEG_16BIT                    32858
#define ID_NEG_32BIT                    32859
#define ID_NEG_64BIT                    32860
#define ID_HIGHLIGHT                    32862
#define ID_HIGHLIGHT_CLEAR              32863
#define ID_HIGHLIGHT_PREV               32864
#define ID_HIGHLIGHT_NEXT               32865
#define ID_CUSTOMIZE                    32866
#define ID_TOOLS_ENTRY                  32867
#define ID_HELP_KEYBOARDMAP             32868
#define ID_WINDOW_MANAGER               32869
#define ID_SEARCH                       32870
#define ID_JUMP_HEX                     32872
#define ID_JUMP_HEX_START               32873
#define ID_JUMP_DEC                     32874
#define ID_JUMP_DEC_START               32875
#define ID_SELECT_LINE                  32876
#define ID_SEARCH_COMBO                 32877
#define ID_JUMP_HEX_COMBO               32878
#define ID_JUMP_DEC_COMBO               32879
#define ID_SCHEME_COMBO                 32880
#define ID_SCHEME_COMBO_US              32881
#define ID_BOOKMARKS_COMBO              32882
#define ID_HELP_WEB                     32885
#define ID_HELP_FORUM                   32886
#define ID_HELP_FAQ                     32887
#define ID_HELP_HOMEPAGE                32888
#define ID_HELP_REGISTER                32889
#define ID_VIEW_USER_TOOLBAR1           32901
#define ID_VIEW_USER_TOOLBAR2           32902
#define ID_VIEW_USER_TOOLBAR3           32903
#define ID_VIEW_USER_TOOLBAR4           32904
#define ID_VIEW_USER_TOOLBAR5           32905
#define ID_VIEW_USER_TOOLBAR6           32906
#define ID_VIEW_USER_TOOLBAR7           32907
#define ID_VIEW_USER_TOOLBAR8           32908
#define ID_VIEW_USER_TOOLBAR9           32909
#define ID_VIEW_USER_TOOLBAR10          32910
#define ID_OR_BYTE                      32911
#define ID_OR_16BIT                     32912
#define ID_OR_32BIT                     32913
#define ID_OR_64BIT                     32914
#define ID_ASC2EBC                      32920
#define ID_EBC2ASC                      32921
#define ID_ANSI2IBM                     32922
#define ID_IBM2ANSI                     32923
#define ID_UPPERCASE                    32924
#define ID_LOWERCASE                    32925
#define ID_ENCRYPT_ALG                  32926
#define ID_ENCRYPT_PASSWORD             32927
#define ID_ENCRYPT_CLEAR                32928
#define ID_ENCRYPT_ENCRYPT              32929
#define ID_ENCRYPT_DECRYPT              32930
#define ID_EDIT_APPENDFILE              32931
#define ID_EDIT_APPENDSAMEFILE          32932
#define ID_UNDO_CHANGES                 32933
#define ID_ZLIB_SETTINGS                32934
#define ID_ZLIB_COMPRESS                32935
#define ID_ZLIB_DECOMPRESS              32936
#define ID_IMPORT_HEX_TEXT              32940
#define ID_IMPORT_MOTOROLA_S            32941
#define ID_IMPORT_INTEL                 32942
#define ID_EXPORT_HEX_TEXT              32943
#define ID_EXPORT_S1                    32944
#define ID_EXPORT_S2                    32945
#define ID_EXPORT_S3                    32946
#define ID_EXPORT_INTEL                 32947
#define ID_BOOKMARKS_EDIT               32950
#define ID_BOOKMARKS_CLEAR              32951
#define ID_BOOKMARKS_PREV               32952
#define ID_BOOKMARKS_NEXT               32953
#define ID_BOOKMARKS_HIDE               32954
#define ID_BOOKMARKS                    32955
#define ID_BOOKMARK_TOGGLE              32956
#define ID_PRINTERARGS_PAGENUMBER       32958
#define ID_PRINTERARGS_CURRENTDATE      32959
#define ID_PRINTERARGS_CURRENTTIME      32960
#define ID_PRINTERARGS_LONGFORMATDATETIME 32961
#define ID_PRINTERARGS_FILECREATIONDATETIME 32962
#define ID_PRINTERARGS_FILECHANGEDDATETIME 32963
#define ID_PRINTERARGS_FILEACCESSDDATETIME 32964
#define ID_PRINTERARGS_FULLNAME         32965
#define ID_PRINTERARGS_FILENAME         32966
#define ID_CALC_SEL                     32969
#define ID_DISPLAY_RESET                32970
#define ID_DISPLAY_DROPDOWN             32971
#define ID_CHARSET_DROPDOWN             32972
#define ID_CONTROL_DROPDOWN             32973
#define ID_DISPLAY_HEX                  32974
#define ID_DISPLAY_CHAR                 32975
#define ID_DISPLAY_BOTH                 32976
#define ID_CHARSET_EBCDIC               32977
#define ID_CHARSET_ASCII                32978
#define ID_CHARSET_ANSI                 32979
#define ID_CHARSET_OEM                  32980
#define ID_CONTROL_NONE                 32981
#define ID_CONTROL_ALPHA                32982
#define ID_CONTROL_C                    32983
#define ID_DISPLAY_STACKED              32984
#define ID_VIEW_VIEWBAR                 32987
#define ID_SCHEME                       32988
#define ID_MACRO_MESSAGE                32989
#define ID_KEEP_TIMES                   32990
#define ID_CHECKSUM8                    32991
#define ID_CHECKSUM16                   32992
#define ID_CHECKSUM32                   32993
#define ID_CHECKSUM64                   32994
#define ID_CRC16                        32995
#define ID_CRC32                        32996
#define ID_CRC_CCITT                    32997
#define ID_MD5                          32998
#define ID_XOR_BYTE                     33001
#define ID_XOR_16BIT                    33002
#define ID_XOR_32BIT                    33003
#define ID_XOR_64BIT                    33004
#define ID_ASSIGN_BYTE                  33005
#define ID_ASSIGN_16BIT                 33006
#define ID_ASSIGN_32BIT                 33007
#define ID_ASSIGN_64BIT                 33008
#define ID_ADD_BYTE                     33009
#define ID_ADD_16BIT                    33010
#define ID_ADD_32BIT                    33011
#define ID_ADD_64BIT                    33012
#define ID_SUBTRACT_BYTE                33013
#define ID_SUBTRACT_16BIT               33014
#define ID_SUBTRACT_32BIT               33015
#define ID_SUBTRACT_64BIT               33016
#define ID_AND_BYTE                     33017
#define ID_AND_16BIT                    33018
#define ID_AND_32BIT                    33019
#define ID_AND_64BIT                    33020
#define ID_GTR_BYTE                     33021
#define ID_GTR_16BIT                    33022
#define ID_GTR_32BIT                    33023
#define ID_GTR_64BIT                    33024
#define ID_LESS_BYTE                    33025
#define ID_LESS_16BIT                   33026
#define ID_LESS_32BIT                   33027
#define ID_LESS_64BIT                   33028
#define ID_MUL_BYTE                     33029
#define ID_MUL_16BIT                    33030
#define ID_MUL_32BIT                    33031
#define ID_MUL_64BIT                    33032
#define ID_DIV_BYTE                     33033
#define ID_DIV_16BIT                    33034
#define ID_DIV_32BIT                    33035
#define ID_DIV_64BIT                    33036
#define ID_MOD_BYTE                     33037
#define ID_MOD_16BIT                    33038
#define ID_MOD_32BIT                    33039
#define ID_MOD_64BIT                    33040
#define ID_REV_BYTE                     33041
#define ID_REV_16BIT                    33042
#define ID_REV_32BIT                    33043
#define ID_REV_64BIT                    33044
#define ID_SUBTRACT_X_BYTE              33045
#define ID_SUBTRACT_X_16BIT             33046
#define ID_SUBTRACT_X_32BIT             33047
#define ID_SUBTRACT_X_64BIT             33048
#define ID_DIV_X_BYTE                   33049
#define ID_DIV_X_16BIT                  33050
#define ID_DIV_X_32BIT                  33051
#define ID_DIV_X_64BIT                  33052
#define ID_MOD_X_BYTE                   33053
#define ID_MOD_X_16BIT                  33054
#define ID_MOD_X_32BIT                  33055
#define ID_MOD_X_64BIT                  33056
#define ID_RECENT_FILES                 33062
#define ID_HIGHLIGHT_HIDE               33065
#define ID_BANNED                       33066
#define ID_VIEW_NAVBAR                  33067
#define ID_VIEW_FORMATBAR               33068
#define ID_FIND_NEXT                    33070
#define ID_BOOKMARK_ALL                 33071
#define ID_REPLACE                      33072
#define ID_REPLACE_ALL                  33073
#define IDC_FONTNAME                    33076
#define IDC_FONTSIZE                    33077
#define ID_COLUMN_DEC                   33078
#define ID_COLUMN_INC                   33079
#define ID_DFFD_EXPANDALL               33080
#define ID_DFFD_EDIT_MODE               33081
#define ID_DFFD_VIEW_MODE               33082
#define ID_DFFD_INSERT_STRUCT           33083
#define ID_DFFD_INSERT_JUMP             33084
#define ID_DFFD_INSERT_FOR              33085
#define ID_DFFD_INSERT_IF               33086
#define ID_DFFD_INSERT_EVAL             33087
#define ID_DFFD_INSERT_DATA             33088
#define ID_DFFD_INSERT_DEFINE_STRUCT    33089
#define ID_DFFD_INSERT_USE_STRUCT       33090
#define ID_DFFD_EDIT                    33091
#define ID_DFFD_BYTE                    33092
#define ID_DFFD_WORD                    33093
#define ID_DFFD_DWORD                   33094
#define ID_DFFD_QWORD                   33095
#define ID_DFFD_ENCLOSE_STRUCT          33096
#define ID_DFFD_ENCLOSE_FOR             33097
#define ID_DFFD_ENCLOSE_IF              33098
#define ID_DFFD_ENCLOSE_JUMP            33099
#define ID_DFFD_INSERT_SWITCH           33100
#define ID_DFFD_DELETE                  33101
#define ID_DFFD_GLOBAL                  33102
#define ID_HIGHLIGHT_MENU               33108
#define ID_MARK_MENU                    33109
#define ID_BOOKMARKS_MENU               33110
#define ID_DFFD_WEB                     33112
#define ID_DFFD_PARSE_DECLARATIONS      33115
#define ID_RAND_BYTE                    33117
#define ID_RAND_16BIT                   33118
#define ID_RAND_32BIT                   33119
#define ID_RAND_64BIT                   33120
#define ID_RAND_FAST                    33121
#define ID_RAND_SEED                    33124
#define ID_RAND_SEED_CALC               33125
#define ID_TRACK_CHANGES                33126
#define ID_INSERT_BLOCK                 33127
#define ID_TAB_ICONS                    33128
#define ID_TABS_AT_BOTTOM               33129
#define ID_TOGGLE_ENDIAN                33130
#define ID_BIG_ENDIAN                   33131
#define ID_LITTLE_ENDIAN                33132
#define ID_REPAIR_DIALOGBARS            33134
#define ID_REPAIR_CUST                  33135
#define ID_REPAIR_SETTINGS              33136
#define ID_REPAIR_ALL                   33137
#define ID_REPAIR_CHECK                 33138
#define ID_HELP_TUTE1                   33140
#define ID_HELP_TUTE2                   33141
#define ID_HELP_TUTE3                   33142
#define ID_VIEW_CALCULATOR              33150
#define ID_VIEW_BOOKMARKS               33151
#define ID_VIEW_FIND                    33152
#define ID_VIEW_PROPERTIES              33153
#define ID_VIEW_EXPL                    33154
#define ID_ROL_BYTE                     33160
#define ID_ROL_16BIT                    33161
#define ID_ROL_32BIT                    33162
#define ID_ROL_64BIT                    33163
#define ID_ROR_BYTE                     33164
#define ID_ROR_16BIT                    33165
#define ID_ROR_32BIT                    33166
#define ID_ROR_64BIT                    33167
#define ID_LSL_BYTE                     33168
#define ID_LSL_16BIT                    33169
#define ID_LSL_32BIT                    33170
#define ID_LSL_64BIT                    33171
#define ID_LSR_BYTE                     33172
#define ID_LSR_16BIT                    33173
#define ID_LSR_32BIT                    33174
#define ID_LSR_64BIT                    33175
#define ID_ASR_BYTE                     33176
#define ID_ASR_16BIT                    33177
#define ID_ASR_32BIT                    33178
#define ID_ASR_64BIT                    33179
#define ID_GTRU_BYTE                    33180
#define ID_GTRU_16BIT                   33181
#define ID_GTRU_32BIT                   33182
#define ID_GTRU_64BIT                   33183
#define ID_LESSU_BYTE                   33184
#define ID_LESSU_16BIT                  33185
#define ID_LESSU_32BIT                  33186
#define ID_LESSU_64BIT                  33187
#define ID_DIALOGS_DOCKABLE             33200
#define ID_EXPLORER_OPEN                33201
#define ID_EXPLORER_OPEN_RO             33202
#define ID_NAV_BACK                     33990
#define ID_NAV_FORW                     33991
#define ID_FILE_OPEN_SPECIAL            33992
#define ID_NAV_BACK_FIRST               34000
#define ID_NAV_FORW_FIRST               36000
#define ID_DFFD_OPEN_FIRST              38000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        376
#define _APS_NEXT_COMMAND_VALUE         39001
#define _APS_NEXT_CONTROL_VALUE         1534
#define _APS_NEXT_SYMED_VALUE           252
#endif
#endif
