#pragma once

// Note: This file was previously generated by SubWCRev.exe (when SVN was used for source control).
// Now they are updated manually until we can do a simialr thing using Git.
#define SVNRevision 1400
#define SVNRevisionStr "1400"
char *SVNDate     = "2016/01/01 05:00:00";

